RegisterNetEvent("ud-apartments:EnterApartment")
AddEventHandler("ud-apartments:EnterApartment", function(instanceId)
    exports['ud-interface']:Notify('success', 'Entered Apartment!')
    TriggerServerEvent('InteractSound_SV:PlayOnSource', 'DoorOpen', 1)
    local playerPed = PlayerPedId()
    TeleportPlayer(playerPed, Config.EnterApartmentCoords, Config.EnterApartmentHeading)
end)

RegisterNetEvent("ud-apartments:ExitApartment")
AddEventHandler("ud-apartments:ExitApartment", function()
    exports['ud-interface']:Notify('success', 'Exited Apartment!')
    TriggerServerEvent('InteractSound_SV:PlayOnSource', 'DoorClose', 1)
    local playerPed = PlayerPedId()
    TeleportPlayer(playerPed, Config.ExitApartmentCoords, Config.ExitApartmentHeading)
end)

RegisterNetEvent("ud-apartments:JoinApartment")
AddEventHandler("ud-apartments:JoinApartment", function(instanceId)
    exports['ud-interface']:Notify('success', 'Joined Apartment BWO!')
    TriggerServerEvent('InteractSound_SV:PlayOnSource', 'DoorOpen', 1)
    local playerPed = PlayerPedId()
    TeleportPlayer(playerPed, Config.EnterApartmentCoords, Config.EnterApartmentHeading)
end)

RegisterNetEvent("ud-apartments:InvitePlayer")
AddEventHandler("ud-apartments:InvitePlayer", function(targetPlayerId)
    TriggerServerEvent('ud-apartments:server:InvitePlayer', targetPlayerId)
end)

RegisterNetEvent("ud-apartments:NotifyInvite")
AddEventHandler("ud-apartments:NotifyInvite", function(invitingPlayerId)
    exports['ud-interface']:Notify('success', 'You have been invited to an apartment! Use /acceptinvite to join.')
end)

RegisterNetEvent('ud-apartments:enterApartmentserverside')
AddEventHandler('ud-apartments:enterApartmentserverside', function()
    TriggerServerEvent('ud-apartments:server:EnterApartment')
end)

RegisterNetEvent('ud-apartments:exitApartmentserverside')
AddEventHandler('ud-apartments:exitApartmentserverside', function()
    TriggerServerEvent('ud-apartments:server:ExitApartment')
end)

RegisterNetEvent('ud-apartments:OpenStorage')
AddEventHandler('ud-apartments:OpenStorage', function()
    local playerId = GetPlayerServerId(PlayerId())
    TriggerServerEvent('ud-apartments:RequestStorage', playerId)
end)

RegisterNetEvent('ud-apartments:OpenStorageClient')
AddEventHandler('ud-apartments:OpenStorageClient', function(stashId)
    exports.ox_inventory:openInventory('stash', stashId)
end)